INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('ZH','Zürich',now,now,now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('BE','Bern',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('LU','Luzern',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('UR','Uri',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SZ','Schwyz',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('OW','Obwalden',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('NW','Nidwalden',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('GL','Glarus',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('ZG','Zug',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('FR','Fribourg',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SO','Solothurn',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('BS','Basel-Stadt',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('BL','Basel-Landschaft',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SH','Schaffhausen',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('AR','Appenzell Ausserrhoden',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('AI','Appenzell Innerrhoden',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SG','St. Gallen',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('GR','Graubünden',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('AG','Aargau',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('TG','Thurgau',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('TI','Ticino',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('VD','Vaud',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('VS','Valais',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('NE','Neuchâtel',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('GE','Genève',now,now);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('JU','Jura',now,now);
