INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('ZH','Zürich',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('BE','Bern',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('LU','Luzern',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('UR','Uri',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SZ','Schwyz',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('OW','Obwalden',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('NW','Nidwalden',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('GL','Glarus',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('ZG','Zug',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('FR','Fribourg',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SO','Solothurn',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('BS','Basel-Stadt',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('BL','Basel-Landschaft',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SH','Schaffhausen',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('AR','Appenzell Ausserrhoden',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('AI','Appenzell Innerrhoden',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('SG','St. Gallen',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('GR','Graubünden',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('AG','Aargau',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('TG','Thurgau',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('TI','Ticino',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('VD','Vaud',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('VS','Valais',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('NE','Neuchâtel',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('GE','Genève',current_timestamp,current_timestamp);
INSERT INTO cantons (code,name,created_at,updated_at) VALUES ('JU','Jura',current_timestamp,current_timestamp);
